### ISSUE TITLE
Won't read commands from other players

### ISSUE THREAD

**Issue by StormFireFox1** [teeli/irc-cah#21]
The Bot connects and does everything it should. However, the bot only responds to my own commands, no one else's. Can't seem to find the issue.

**Comment by teeli** [comment]
I've never run into this issue when testing the. Of course it should receive commands from all people in the channel (restricting certain commands, like !stop to operators only is a feature I'd like to implement in the future, but as of now, all commands should work for everyone)

Can you give some more info? Are all other users channel operators or regular users? What channel modes are enabled? Which network is the channel in?

**Comment by teeli** [comment]
Sorry, accidentally closed this. Haven't had my morning coffee yet.

**Comment by StormFireFox1** [comment]
The channel is on a private IRC network of mine. The bot connects and is OP'ed. I am personally an oper and it reads my commands. Other normal users don't read them, and I've even -o'd myself and it does only read me. Channel modes are default, +CQGnt.

**Comment by teeli** [comment]
Well, I honestly don't know what could be causing that. I've mostly tested this in IRCnet, where it works fine in a situation like what you're describing, so all I can think of is that the bot is running in some kind of restricted mode, where it just isn't receiving any user messages at all, in your network. I don't see anything in the channel modes either, that could cause this.

**Comment by StormFireFox1** [comment]
It's fine now, I got it fixed. Turns out I messed too much with the original clone and started changing some of the commands by accident. Also, the bot seems to need to be +o'ed for the bot to work properly.
